name: Netlify Deployment

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install # Replace with your build command if using a different tool

    - name: Build
      run: npm run build # Replace with your build command if using a different tool

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Netlify
      uses: uses: netlify/actions/cli@v3.0.0
      with:
        args: deploy --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
